apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gtd.configmap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gtd.labels" . | nindent 4 }}
data:
  PG_USER: {{ .Values.db.user }}
  PG_NAME: {{ .Values.db.name }}
