apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gtd.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels: &labels
    {{- include "gtd.labels" . | nindent 4 }}
    tier: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: db
        image: "{{ .Values.db.image }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.db.imagePullPolicy }}
        args:
        - -c
        - shared_buffers=256MB
        resources:
          requests:
            cpu: 250m
            memory: 384Mi
          limits:
            cpu: 1000m
        ports:
        - name: tcp-postgresql
          containerPort: &port 5432
        livenessProbe: &probe
          tcpSocket:
            port: *port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe: *probe
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: &configmap {{ template "gtd.configmap.fullname" . }}
              key: PG_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gtd.secret.fullname" . }}
              key: PG_PASS
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: *configmap
              key: PG_NAME
        - name: PGDATA
          value: &pgdata-path /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: &pgdata-vol pgdata
          mountPath: *pgdata-path
  volumeClaimTemplates:
  - metadata:
      name: *pgdata-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 128Mi
