apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gtd.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gtd.labels" . | nindent 4 }}
type: Opaque
data:
  PG_PASS: {{ default (randAlphaNum 16) .Values.db.pass | b64enc }}
  SECRET_KEY: {{ default (randAlphaNum 32) .Values.app.secret_key | b64enc }}
